module.exports = function () {
  return {
    products: [
      {
        id: 1,
        name: "Samsung S8",
        price: 1000,
        imageUrl: "1.jpg",
        description: "normal product",
        category: "Phone",
      },
      {
        id: 2,
        name: "Samsung S9",
        price: 1500,
        imageUrl: "2.jpg",
        description: "normal product",
        category: "Phone",
      },
      {
        id: 3,
        name: "Samsung S10",
        price: 2000,
        imageUrl: "3.jpg",
        description: "good product",
        category: "Phone",
      },
      {
        id: 4,
        name: "Samsung S10 plus",
        price: 3000,
        imageUrl: "4.jpg",
        description: "normal product",
        category: "Phone",
      },
      {
        id: 5,
        name: "Samsung A7 2018",
        price: 800,
        imageUrl: "5.jpg",
        description: "normal product",
        category: "Phone",
      },
      {
        id: 6,
        name: "Acer",
        price: 1100,
        imageUrl: "acer.jpg",
        description: "normal product",
        category: "Computer",
      },
      {
        id: 7,
        name: "Acer Swift",
        price: 1420,
        imageUrl: "acer2.jpg",
        description: "normal product",
        category: "Computer",
      },
      {
        id: 8,
        name: "IPhone X",
        price: 2500,
        imageUrl: "8.jpg",
        description: "normal product",
        category: "Phone",
      },
      {
        id: 9,
        name: "Music System",
        price: 3200,
        imageUrl: "lg.jpg",
        description: "best product",
        category: "Electronics",
      },
      {
        id: 10,
        name: "Canon Camera",
        price: 3200,
        imageUrl: "camera.jpg",
        description: "best product",
        category: "Electronics",
      },
    ],
    categories: [
      { id: 1, name: "Phone" },
      { id: 2, name: "Computer" },
      { id: 3, name: "Electronics" },
    ],
    orders: [],
  };
};
